steps:
  # Step 1: Build Flutter APK
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/cce9b8d9-aa03-4985-a0e/mentrix-apk:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    id: 'build-apk-docker'

  # Step 2: Push to Cloud Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/cce9b8d9-aa03-4985-a0e/mentrix-apk:latest'
    id: 'push-artifact'

artifacts:
  objects:
    location: 'gs://cce9b8d9-aa03-4985-a0e-build-artifacts/apk'
    paths:
      - 'mentrix_student_app/build/outputs/apk/release/*.apk'

timeout: '3600s'
