steps:
  # Clone Flutter repo
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/flutter/flutter.git', '/workspace/flutter']

  # Set Flutter PATH
  - name: 'gcr.io/cloud-builders/gcloud'
    env:
      - 'PATH=/workspace/flutter/bin:$PATH'
    args: ['--version']

  # Build APK
  - name: 'gcr.io/cloud-builders/gcloud'
    env:
      - 'PATH=/workspace/flutter/bin:$PATH'
    args:
      - 'bash'
      - '-c'
      - |
        cd /workspace/mentrix_student_app
        flutter pub get
        flutter build apk --release

timeout: '3600s'

options:
  logging: CLOUD_LOGGING_ONLY
